---

# top-level

- name: install mongo 
  include: install.yml tags=install

- name: create key
  include: keygen.yml tags=keygen

- name: configure mongo 
  include: configure.yml tags=configure

- name: configure config server 
  include: configure_cs.yml tags=configure_cs

- name: configure mongos servers
  include: configure_mongos.yml tags=configure_mongos

- name: add shards
  include: shards.yml tags=add_shards

#- name: uninstall mongo 
#  include: uninstall.yml tags=uninstall
