---

# top-level

- name: install mongo 
  include: install.yml tags=install

- name: configure mongo 
  include: configure.yml tags=configure

- name: add shards
  include: shards.yml tags=add_shards
